use_frameworks!

platform :ios, '11.0'

target 'RxListDataSource_Example' do
  pod 'RxListDataSource', :path => '../'
  
  target 'RxListDataSource_Tests' do
    inherit! :search_paths
    
  end
end
